import turtle,time
kouki = turtle.Turtle()
kouki.color("orange")
kouki.forward(100)
time.sleep(1)
kouki.left(90)
kouki.color("yellow")
kouki.forward(100)
time.sleep(1)
kouki.left(90)
kouki.color("blue")
kouki.forward(100)
time.sleep(1)
kouki.left(90)
kouki.color("green")
kouki.forward(100)
time.sleep(1)
kouki.left(90)